agenda/urls.py
from django.urls import path, include
from agenda import views

app_name = 'agenda'

urlpatterns = [
    path('', views.index, name='index'),
    path('autocadastro/', views.autocadastro, name='autocadastro'),
    path('minhas_vacinas/<int:paciente_pk>', views.minhas_vacinas, name='minhas_vacinas'),
    path(r'campanhas/', include([
        path('', views.campanhas, name='campanhas'),
        path('<int:pk>', views.detalhar_campanha, name='detalhar_campanha'),
        path('<int:pk>/editar/', views.editar_campanha, name='editar_campanha'),
        path('cadastrar/', views.cadastrar_campanha, name='cadastrar_campanha'),
    ])),
    path(r'agendar_vacinacao/', include([
        path('<int:campanha_pk>/', views.agendar_vacinacao_estabelecimento, name='agendar_vacinacao_estabelecimento'),
        path('<int:campanha_pk>/<int:estabelecimento_pk>/', views.agendar_vacinacao_data, name='agendar_vacinacao_data'),
    ])),
    
    path(r'acompanhar_vacinacao/', include([
        path('<int:agendamento_pk>/fila/', views.fila, name='fila'),
    ])),
    
    path('<int:agendamento_pk>/confirmar_vacinacao/', views.confirmar_vacinacao, name='confirmar_vacinacao'),
    path('cadastrar_vacina_privada/', views.cadastrar_vacina_privada, name='cadastrar_vacina_privada')

]

vacinas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.contrib.auth import views as auth_views
from vacinas import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestao/', include('gestao.urls')),
    path('agenda/', include('agenda.urls')),
    path('', include('social_django.urls', namespace='social')),
    path("select2/", include("django_select2.urls")),
    path('', views.index),
    path('accounts/login/', auth_views.LoginView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [ url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }), url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_ROOT }), ]

agenda/models.py
from django.db import models
from django.db.models import Sum, Max, Count
from gestao.models import Estabelecimento, Paciente

# Create your models here.
class Campanha(models.Model):
    titulo = models.CharField(max_length=255)
    data_inicio = models.DateField(u'Data de inicio', null=True)
    data_fim = models.DateField(u'Data de fim', null=True)
    estabelecimentos = models.ManyToManyField(Estabelecimento)

    def __str__(self):
        return self.titulo

    def estoque_cadastrado(self):
        if self.estoque_set.exists():
            return self.estoque_set.aggregate(qtd=Sum('quantidade'))['qtd']
        return 0

    def estoque_disponivel(self):
        disponiveis = 0
        if self.estoque_set.exists():
            total_cadastrado = self.estoque_set.aggregate(qtd=Sum('quantidade'))['qtd']
            disponiveis = total_cadastrado

        if self.agendamento_set.exists():
            aplicadas = self.agendamento_set.filter(status=Agendamento.APLICADA).aggregate(total=Count('pk'))['total']
            disponiveis -= aplicadas

        return disponiveis

    def agendamentos(self):
        if self.agendamento_set.exists():
           return self.agendamento_set.aggregate(total=Count('pk'))['total']


class Estoque(models.Model):
    quantidade = models.IntegerField('Quantidade de Vacinas')
    estabelecimento = models.ForeignKey(Estabelecimento, on_delete=models.CASCADE)
    campanha = models.ForeignKey(Campanha, on_delete=models.CASCADE)
    lote = models.CharField('Lote', max_length=20, default=None, null=True)

    def __str__(self):
        return f'{self.campanha.titulo} (Lote: {self.lote})'


class Agendamento(models.Model):
    OCUPADO = 'Ocupado'
    DISPONIVEL = 'Disponível'
    APLICADA = 'Aplicada'
    STATUS_CHOICE = (
        (OCUPADO, OCUPADO),
        (APLICADA, APLICADA),
        (DISPONIVEL, DISPONIVEL),
    )
    status = models.CharField('Status', max_length=30, choices=STATUS_CHOICE, default=DISPONIVEL)
    data = models.DateField(u'Data de Vacinação')
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True)
    estabelecimento = models.ForeignKey(Estabelecimento, on_delete=models.CASCADE)
    campanha = models.ForeignKey(Campanha, on_delete=models.CASCADE)
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE, null=True)
    data_aplicacao = models.DateTimeField(u'data_aplicacao', null=True)

    def foi_aplicada(self):
        if self.status == Agendamento.APLICADA:
            return True
        return False

    def foi_marcada(self):
        if self.status == Agendamento.OCUPADO:
            return True
        return False

class Vacina(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True)
    estabelecimento = models.ForeignKey(Estabelecimento, on_delete=models.CASCADE)
    campanha = models.ForeignKey(Campanha, on_delete=models.CASCADE)
    estoque = models.ForeignKey(Estoque, on_delete=models.CASCADE, null=True)
    agendamento = models.ForeignKey(Agendamento, on_delete=models.CASCADE, null=True)

class VacinaPrivada(models.Model):
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True)
    descricao = models.CharField('Descrição', max_length=255)
    estabelecimento = models.CharField('Estabelecimento de Aplicação', max_length=255)
    data_vacinacao = models.DateField(u'Data de vacinação', null=True)
    lote = models.CharField('Estabelecimento de Aplicação', max_length=255)
    

agenda/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from gestao.forms import PessoaFisicaForm
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from gestao.models import Paciente, PessoaFisica, User, Estabelecimento
from django.db import transaction
from agenda.forms import CampanhaForm, AgendarVacinacaoEstabelecimentoForm, \
                         AgendarVacinacaoDataForm, ConfirmacaoVacinaForm, \
                         VacinaPrivadaForm
from agenda.models import Campanha, Agendamento, Vacina, VacinaPrivada
from datetime import datetime, date
from django.core.mail import send_mail
        
@login_required
def index(request):    
    minhas_vacinas = Agendamento.objects.filter(paciente=request.user.paciente(), 
                                        status__in=[Agendamento.APLICADA, Agendamento.OCUPADO])
    vacinas_pendentes = Agendamento.objects.filter(paciente=request.user.paciente())
    campanhas_ativas = Campanha.objects.filter(data_inicio__lte=date.today(), 
                                                        data_fim__gte=date.today())
    campanhas_sem_agendas = campanhas_ativas.exclude(pk__in=minhas_vacinas.values_list('campanha', flat=True))
    
    return render(request, 'agenda/index.html', locals())

@login_required
@transaction.atomic
def autocadastro(request):
    title = 'Autocadastro de Paciente'
    instance = PessoaFisica.objects.filter(cpf=request.user.username).first()
    form = PessoaFisicaForm(data=request.POST or None, instance=instance)
    if form.is_valid():
        pessoa_fisica = form.save(commit=False)
        user, created = User.objects.get_or_create(username=form.cleaned_data['cpf'].replace('-', '').replace('.', ''))
        pessoa_fisica.user = user
        pessoa_fisica.save()

        paciente = Paciente.objects.create(pessoa_fisica=pessoa_fisica)

        return HttpResponseRedirect(reverse('agenda:index'))
    return render(request, 'gestao/form_base.html', locals())


@login_required
def minhas_vacinas(request, paciente_pk):
    title = 'Minhas Vacinas'
    paciente = get_object_or_404(Paciente, pk=paciente_pk)    
    vacinas_publicas = Vacina.objects.filter(paciente=paciente)
    vacinas_privadas = VacinaPrivada.objects.filter(paciente=paciente)

    return render(request, 'agenda/minhas_vacinas.html', locals())


@login_required
def campanhas(request):
    title = 'Campanhas'
    campanhas = Campanha.objects.all()
    return render(request, 'agenda/campanhas.html', locals())


@login_required
def detalhar_campanha(request, pk):
    title = 'Campanhas'
    return render(request, 'agenda/minhas_vacinas.html', locals())


@login_required
def editar_campanha(request, pk):
    title = 'Editar Campanha'
    campanha = get_object_or_404(Campanha, pk=pk)    
    form = CampanhaForm(data=request.POST or None, instance=campanha)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('agenda:campanhas'))
    return render(request, 'gestao/form_base.html', locals())


@login_required
def cadastrar_campanha(request):
    title = 'Campanhas'
    form = CampanhaForm(data=request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('agenda:campanhas'))
    return render(request, 'gestao/form_base.html', locals())

@login_required
def cadastrar_campanha(request):
    title = 'Campanhas'
    form = CampanhaForm(data=request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('agenda:campanhas'))
    return render(request, 'gestao/form_base.html', locals())

@login_required
def agendar_vacinacao_estabelecimento(request, campanha_pk):
    title = 'Agendar Vacinação - Escolha de Estabelecimento'
    campanha = get_object_or_404(Campanha, pk=campanha_pk)
    form = AgendarVacinacaoEstabelecimentoForm(data=request.POST or None, campanha=campanha)
    if form.is_valid():
        estabelecimento = form.cleaned_data['estabelecimento']
        return HttpResponseRedirect(reverse('agenda:agendar_vacinacao_data', args=(campanha.pk, estabelecimento.pk)))
    return render(request, 'gestao/form_base.html', locals())

@login_required
def agendar_vacinacao_data(request, campanha_pk, estabelecimento_pk):
    title = 'Agendar Vacinação - Escolha da Data'
    campanha = get_object_or_404(Campanha, pk=campanha_pk)
    estabelecimento = get_object_or_404(Estabelecimento, pk=estabelecimento_pk)
    paciente = request.user.paciente()
    form = AgendarVacinacaoDataForm(data=request.POST or None, campanha=campanha,
                                     estabelecimento=estabelecimento, paciente=paciente)
    if form.is_valid():
        form.save()
        #send_mail('[IMUNIZOW] Vacina Agendada', 'Here is the message.', 'from@example.com', ['to@example.com'], fail_silently=True)
        return HttpResponseRedirect(reverse('agenda:index'))
    return render(request, 'gestao/form_base.html', locals())

@login_required
def fila(request, agendamento_pk):
    title = 'Fila de Vacinação'
    agendamento = get_object_or_404(Agendamento, pk=agendamento_pk)
    campanha = get_object_or_404(Campanha, pk=agendamento.campanha.pk)
    estabelecimento = get_object_or_404(Estabelecimento, pk=agendamento.estabelecimento.pk)
    agendamentos = Agendamento.objects.filter(campanha=campanha, estabelecimento=estabelecimento, 
                                                    data=agendamento.data, status=Agendamento.OCUPADO).order_by('pk')
    return render(request, 'agenda/fila.html', locals())

@login_required
def confirmar_vacinacao(request, agendamento_pk):
    title = 'Confirmar Vacinação'
    agendamento = get_object_or_404(Agendamento, pk=agendamento_pk)
    form = ConfirmacaoVacinaForm(data=request.POST or None, agendamento=agendamento)
    if form.is_valid():
        form.save()
        #ProfissionalSaude.objects.filter(estabelecimento=agendamento.estabelecimento)
        #send_mail('[IMUNIZOW] Vacina Aplicada', 'Here is the message.', 'from@example.com', ['to@example.com'], fail_silently=True)
        return HttpResponseRedirect(reverse('gestao:agendamentos_estabelecimento', args=(agendamento.estabelecimento.pk,)))
    return render(request, 'gestao/form_base.html', locals())

@login_required
def cadastrar_vacina_privada(request):
    title = 'Cadastro de Vacina Privada'
    paciente = request.user.paciente()
    form = VacinaPrivadaForm(data=request.POST or None, paciente=paciente)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('agenda:index'))
    return render(request, 'gestao/form_base.html', locals())

templates/agenda/campanhas.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link href="{% static 'libs/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/datatables/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/datatables/buttons.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/jquery-toast/jquery.toast.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="page-title">Campanhas</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Agenda</a></li>
                        <li class="breadcrumb-item active">Campanhas</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="padding-bottom: 10px;">
        <div class="col-sm-12 offset-md-8 col-md-4 offset-lg-9 col-lg-3">    
            <a href="{% url 'agenda:cadastrar_campanha' %}" class="btn btn-block btn-rounded btn-success pull-right">Cadastrar Campanha</a>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table id="tabela-prestadores" class="table table-striped dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th data-priority="2">#</th>
                                <th data-priority="3">Título</th>
                                <th data-priority="2">Data de Início</th>
                                <th data-priority="2">Data de Fim</th>
                                <th data-priority="2">Ações</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for campanha in campanhas %}
                                <tr id="{{campanha.campanha__id}}">
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{campanha.titulo }}</td>
                                    <td>{{campanha.data_inicio }}</td>
                                    <td>{{campanha.data_fim }}</td>
                                    <td>
                                        <a href="{% url 'agenda:editar_campanha' campanha.pk %}" class="btn btn-primary">Editar</a>
                                        <a href="" class="btn btn-primary">Detalhes</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'libs/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'libs/datatables/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.html5.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.flash.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.print.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.select.min.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.10.20/sorting/datetime-moment.js"></script>
    <script>
        $(document).ready(function() {
            //Buttons examples
            $('#tabela-prestadores').DataTable({
                "lengthMenu": [6, 12, 24, 48, 96],
                "pageLength": 48,
                "language": {
                    "paginate": {
                        "previous": "<i class='mdi mdi-chevron-left'>",
                        "next": "<i class='mdi mdi-chevron-right'>"
                    },
                    "search": "Buscar:",
                    "info": "Exibindo registros de _START_ a _END_ para um total _TOTAL_ registros",
                    "emptyTable": "Nenhum registro encontrado",
                    "infoEmpty": "",
                    "loadingRecords": "Carregando fila...",
                    "processing": "Buscando registros...",
                    "zeroRecords": "Nenhum registro encontrado",
                    "lengthMenu": "Exibindo até _MENU_ registros por página"
                },
                "drawCallback": function () {
                    $('.dataTables_paginate > .pagination').addClass('pagination-rounded');
                }
            });
        });
    </script>
{% endblock %}

templates/agenda/index.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'libs/daterangepicker/daterangepicker.css' %}" />
    <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.3.0/main.min.css' rel='stylesheet' />
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.3.0/main.min.js'></script>  
    <link rel="stylesheet" href="{% static 'libs/sweetalert2/sweetalert2.min.css' %}">
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-flex align-items-center justify-content-between">
            <h4 class="page-title">Agenda</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item active">Agenda</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-7 col-lg-7 col-sm-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Calendário de Vacinação</h4>
            </div>
            <div class="card-body">
                <div id='calendar'></div>
            </div>
        </div>
    </div>
     
    <div class="col-md-5 col-lg-5 col-sm-12">
        <div class="card">
            <div class="card-header">
                <h4 class="header-title mt-0 mb-3">Campanhas de Vacinação Ativa</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead>
                            <tr>
                                <th>Campanha</th>
                                <th>Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for agendamento in minhas_vacinas %}
                                {% if agendamento.foi_marcada %}
                                    <tr>
                                        <td>{{agendamento.campanha.titulo}}</td>
                                        <td>
                                            <a href="{% url 'agenda:fila' agendamento.pk %}" class="btn btn-primary">Acompanhar Fila</a>
                                        </td>
                                    </tr>
                                {% endif %}
                            {% endfor %}

                            {% for campanha in campanhas_sem_agendas %}
                                <tr>
                                    <td>{{campanha.titulo}}</td>
                                    <td>
                                        <a href="{% url 'agenda:agendar_vacinacao_estabelecimento' campanha.pk %}" class="btn btn-success">Agendar</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>  
        </div>
     </div>
</div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'libs/sweetalert2/sweetalert2.min.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                themeSystem: 'bootstrap',
                locale: 'pt-br',
                validRange: {
                    start: '2019-12-15',
                    //end: new Date()
                },
                events: [
                    {% for vac in vacinas_pendentes %}
                        {
                            title: '{{vac.campanha.titulo}}',
                            start: '{{vac.data|date:"Y-m-d"}}',
                            extendedProps: {
                                estabelecimento: '{{ vac.estabelecimento.nome }}',
                                endereco: '{{ vac.estabelecimento.get_endereco }}',
                                status: '{{ vac.status }}'
                            },
                        },
                    {% endfor %}
                ],
                eventClick: function(info) {
                    if (info.event.extendedProps.status == 'Aplicada'){
                        Swal.fire(
                            'Vacina Aplicada!',
                            'Vacina no estabelecimento: '+info.event.extendedProps.estabelecimento+',\nno endereço: '+
                            info.event.extendedProps.endereco,
                            'success'
                            )
                        info.el.style.borderColor = 'red';
                    }else{
                        Swal.fire(
                            'Vacina a vista!',
                            'Dirija-se ao estabelecimento: '+info.event.extendedProps.estabelecimento+',\nno endereço: '+
                            info.event.extendedProps.endereco,
                            'success'
                            )
                        info.el.style.borderColor = 'red';
                    }
                },
            });

            calendar.render();
        });        
    </script>
{% endblock %}

templates/agenda/minhas_vacinas.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link href="{% static 'libs/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/datatables/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/datatables/buttons.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/jquery-toast/jquery.toast.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="page-title">Minhas Vacinas</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Agenda Vacinação</a></li>
                        <li class="breadcrumb-item active">Minhas Vacinas</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="padding-bottom: 10px;">
        <div class="col-sm-12 offset-md-8 col-md-4 offset-lg-9 col-lg-3">
            <a href="{% url 'agenda:cadastrar_vacina_privada' %}"  class="btn btn-block btn-rounded btn-success pull-right">Cadastrar Vacina Privada</a>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table id="tabela-prestadores" class="table table-striped dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th data-priority="2">Data de Aplicação</th>
                                <th data-priority="3">Descrição</th>
                                <th data-priority="2">Estabelecimento</th>
                                <th data-priority="2">Lote da Vacina</th>
                                <th data-priority="2">Origem</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for item in vacinas_publicas%}
                                <tr>
                                    <td>{{ item.agendamento.data_aplicacao|date:'d/m/Y' }}</td>
                                    <td>{{ item.campanha.titulo }}</td>
                                    <td>{{ item.estabelecimento }}</td>
                                    <td>{{ item.estoque.lote }}</td>
                                    <td>
                                        <span class="btn btn-success btn-rounded width-sm waves-effect waves-light">Rede Pública</span>
                                    </td>
                                </tr>
                            {% endfor %}
                            
                            {% for item in vacinas_privadas%}
                                <tr>
                                    <td>{{ item.data_vacinacao|date:'d/m/Y' }}</td>
                                    <td>{{ item.descricao }}</td>
                                    <td>{{ item.estabelecimento }}</td>
                                    <td>{{ item.lote }}</td>
                                    <td>
                                        <span class="btn btn-danger btn-rounded width-sm waves-effect waves-light">Rede Privada</span>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'libs/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'libs/datatables/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.html5.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.flash.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.print.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.select.min.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.10.20/sorting/datetime-moment.js"></script>
    <script>
        $(document).ready(function() {
            //Buttons examples
            $('#tabela-prestadores').DataTable({
                "lengthMenu": [6, 12, 24, 48, 96],
                "pageLength": 48,
                "language": {
                    "paginate": {
                        "previous": "<i class='mdi mdi-chevron-left'>",
                        "next": "<i class='mdi mdi-chevron-right'>"
                    },
                    "search": "Buscar:",
                    "info": "Exibindo registros de _START_ a _END_ para um total _TOTAL_ registros",
                    "emptyTable": "Nenhum registro encontrado",
                    "infoEmpty": "",
                    "loadingRecords": "Carregando fila...",
                    "processing": "Buscando registros...",
                    "zeroRecords": "Nenhum registro encontrado",
                    "lengthMenu": "Exibindo até _MENU_ registros por página"
                },
                "drawCallback": function () {
                    $('.dataTables_paginate > .pagination').addClass('pagination-rounded');
                }
            });
        });
    </script>
{% endblock %}