agenda/urls.py
from django.urls import path, include
from agenda import views

app_name = 'agenda'

urlpatterns = [
    path('', views.index, name='index'),
    path('autocadastro/', views.autocadastro, name='autocadastro'),
    path('minhas_vacinas/<int:paciente_pk>', views.minhas_vacinas, name='minhas_vacinas'),
    path(r'campanhas/', include([
        path('', views.campanhas, name='campanhas'),
        path('<int:pk>', views.detalhar_campanha, name='detalhar_campanha'),
        path('<int:pk>/editar/', views.editar_campanha, name='editar_campanha'),
        path('cadastrar/', views.cadastrar_campanha, name='cadastrar_campanha'),
    ])),
    path(r'agendar_vacinacao/', include([
        path('<int:campanha_pk>/', views.agendar_vacinacao_estabelecimento, name='agendar_vacinacao_estabelecimento'),
        path('<int:campanha_pk>/<int:estabelecimento_pk>/', views.agendar_vacinacao_data, name='agendar_vacinacao_data'),
    ])),
    
    path(r'acompanhar_vacinacao/', include([
        path('<int:agendamento_pk>/fila/', views.fila, name='fila'),
    ])),
    
    path('<int:agendamento_pk>/confirmar_vacinacao/', views.confirmar_vacinacao, name='confirmar_vacinacao'),
    path('cadastrar_vacina_privada/', views.cadastrar_vacina_privada, name='cadastrar_vacina_privada')

]

gestao/urls.py
from django.urls import path, include
from gestao import views

app_name = 'gestao'

urlpatterns = [
    path('sair/', views.sair, name='sair'),
    path('dashboard/<int:estabelecimento_pk>', views.dashboard_estabelecimento, name='dashboard_estabelecimento'),
    path('dashboard/', views.dashboard_geral, name='dashboard_geral'),
    path('municipio/<ibge>', views.busca_municipio),

    path(r'estabelecimentos/', include([
        path('', views.estabelecimentos, name='estabelecimentos'),
        path('<int:pk>', views.detalhar_estabelecimento, name='detalhar_estabelecimento'),
        path('<int:pk>/editar/', views.editar_estabelecimento, name='editar_estabelecimento'),
        path('cadastrar/', views.cadastrar_estabelecimento, name='cadastrar_estabelecimento'),
        path('<int:pk>/habilitar_prestador', views.habilitar_prestador, name='habilitar_prestador'),
        path('<int:pk>/adicionar_profissional/', views.adicionar_profissional, name='adicionar_profissional'),
        path('<int:estabelecimento_pk>/desabilitar_profissional/<int:profissional_pk>', views.desabilitar_profissional, name='desabilitar_profissional'),
        path('<int:estabelecimento_pk>/habilitar_profissional/<int:profissional_pk>', views.habilitar_profissional, name='habilitar_profissional'),
        path('<int:pk>/gestao_vacinas', views.gestao_vacinas, name='gestao_vacinas'),
        path('<int:estabelecimento_pk>/gestao_vacinas/cadastrar_estoque/<int:campanha_pk>/', views.cadastrar_estoque, name='cadastrar_estoque'),
        path('<int:pk>/campanhas/agendamentos', views.agendamentos, name='agendamentos'),
        path('<int:estabelecimento_pk>/agendamentos/cadastrar/<int:campanha_pk>/', views.cadastrar_agendamentos, name='cadastrar_agendamentos'),
        path('<int:pk>/agendamentos', views.agendamentos_estabelecimento, name='agendamentos_estabelecimento'),
    ])),
    
    path(r'coordenadores_sus/', include([
        path('', views.coordenadores_sus, name='coordenadores_sus'),
        path('adicionar/', views.adicionar_coordenador_sus, name='adicionar_coordenador_sus'),
        path('desabilitar_coordenador/<int:coordenador_pk>', views.desabilitar_coordenador, name='desabilitar_coordenador'),
        path('habilitar_coordenador/<int:coordenador_pk>', views.habilitar_coordenador, name='habilitar_coordenador'),        
    ])),
]

vacinas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.contrib.auth import views as auth_views
from vacinas import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestao/', include('gestao.urls')),
    path('agenda/', include('agenda.urls')),
    path('', include('social_django.urls', namespace='social')),
    path("select2/", include("django_select2.urls")),
    path('', views.index),
    path('accounts/login/', auth_views.LoginView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [ url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }), url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_ROOT }), ]

gestao/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

class Estado(models.Model):
    nome = models.CharField(u'Nome', max_length=80)
    codigo = models.CharField(u'Código IBGE', max_length=7, unique=True)

class Municipio(models.Model):
    codigo = models.CharField(u'Código IBGE', max_length=7, unique=True)
    nome = models.CharField(u'Nome', max_length=80)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ('nome', )

    def __str__(self):
        return u'%s / %s' % (self.nome, self.estado.nome)

class PessoaFisica(models.Model):
    SEXO_MASCULINO  = u'M'
    SEXO_FEMININO = u'F'
    SEXO_NAO_INFORMADO = u'N'
    SEXO_CHOICES = (
                        (SEXO_MASCULINO, u'Masculino'),
                        (SEXO_FEMININO, u'Feminino'),
                        (SEXO_NAO_INFORMADO, u'Não Informado')
                    )
    SEXO_FORM_CHOICES = (
                        ('', ''),
                        (SEXO_MASCULINO, u'Masculino'),
                        (SEXO_FEMININO, u'Feminino'),
                    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255)
    cpf = models.CharField(u'CPF',max_length=15, help_text=u'Digite o CPF sem pontos ou traços.', null=True, unique=True)
    sexo = models.CharField(u'Sexo', max_length=1, choices=SEXO_CHOICES, default=SEXO_NAO_INFORMADO)
    data_nascimento = models.DateField(u'Data de Nascimento', null=True)
    telefones = models.CharField(u'Telefones', max_length=60, null=True, blank=True)
    celulares = models.CharField(u'Celulares', max_length=60, null=True, blank=True)
    email = models.CharField(u'Email', max_length=80, null=True, blank=True)
    logradouro = models.CharField(u'Logradouro', max_length=80, null=True, blank=True)
    numero = models.CharField(u'Número', max_length=10, null=True, blank=True)
    complemento = models.CharField(u'Complemento', max_length=80, null=True, blank=True)
    bairro = models.CharField(u'Bairro', max_length=80, null=True, blank=True)
    municipio = models.ForeignKey(Municipio, null=True, blank=True, on_delete=models.CASCADE)
    cep = models.CharField(u'CEP', null=True, blank=True, max_length=15)
    
    class Meta:
        verbose_name = u'Pessoa Fisica'

    def __str__(self):
        return self.nome

    @property
    def idade(self):
        if self.data_nascimento:
            return get_age(self.data_nascimento)

    def get_endereco(self):
        texto = u''
        if self.logradouro:
            texto = texto + self.logradouro

        if self.numero:
            texto = texto + ', '+self.numero

        if self.complemento:
            texto = texto + ' - '+self.complemento

        if self.bairro:
            texto = texto + '. '+self.bairro

        if self.cep:
            texto = texto + '. CEP: '+self.cep +'. '

        if self.municipio:
            texto = texto + ' ' + self.municipio.get_sigla_estado()

        return texto


class Paciente(models.Model):
    pessoa_fisica = models.ForeignKey(PessoaFisica, on_delete=models.CASCADE)
    cartao_sus = models.CharField(u'Cartão Sus', max_length=15, null=True, blank=True)
    
    class Meta:
        verbose_name = u'Paciente'
        verbose_name_plural = u'Pacientes'
        unique_together = ('pessoa_fisica', 'cartao_sus')

    def __str__(self):
        return self.pessoa_fisica.nome

    @property
    def idade(self):
        return self.pessoa_fisica.idade

class Estabelecimento(models.Model):
    cnes = models.CharField(max_length=12, verbose_name=u'Código CNES', unique=True)
    nome = models.CharField(max_length=60)
    razao_social = models.CharField(max_length=60, verbose_name=u'Razão Social', null=True)
    cnpj = models.CharField(max_length=255, verbose_name=u'CNPJ', null=True)
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    logradouro = models.CharField(max_length=60, verbose_name=u'Logradouro', null=True, blank=True)
    num_endereco = models.CharField(max_length=10, verbose_name=u'Número', null=True, blank=True)
    cep = models.CharField(max_length=9, verbose_name=u'CEP', null=True, blank=True)
    telefone = models.CharField(max_length=40, verbose_name=u'Telefone', null=True, blank=True)
    celular = models.CharField(max_length=40, verbose_name=u'Celular', null=True, blank=True)
    email = models.CharField(max_length=100, verbose_name=u'Email', null=True, blank=True)
    complemento = models.CharField(max_length=60, verbose_name=u'Complemento', null=True, blank=True)
    bairro = models.CharField(max_length=60, verbose_name=u'Bairro', null=True, blank=True)
    data_ultima_atualizacao = models.DateTimeField(u'Data da última atualização', null=True)
    ativo = models.BooleanField(verbose_name=u'Ativo',default=True)
    latitude = models.CharField('Latitude', max_length=255, null=True, blank=True)
    longitude = models.CharField('Longitude', max_length=255, null=True, blank=True)
    prestador = models.BooleanField(verbose_name=u'Prestador', default=False)
    
    class Meta:
        verbose_name = u'Estabelecimento de Saúde'
        verbose_name_plural = u'Estabelecimentos de Saúde'
        ordering = ['nome', 'municipio']

    def __str__(self):
        return u'%s (CNES: %s)' % (self.nome, self.cnes)

    def leitos_disponiveis(self):
        return self.leitos.filter(ativo=True, situacao=Leito.DISPONIVEL)

    def get_endereco(self):
        texto = u''
        if self.logradouro:
            texto = texto + self.logradouro

        if self.num_endereco:
            texto = texto + ', '+self.num_endereco

        if self.complemento:
            texto = texto + ' - '+self.complemento

        if self.bairro:
            texto = texto + '. '+self.bairro

        if self.cep:
            texto = texto + '. CEP: '+self.cep

        if self.municipio:
            texto = f'{texto}, {self.municipio.nome} ({self.municipio.estado.nome.upper()})'

        return texto

class ProfissionalSaude(models.Model):
    pessoa_fisica = models.ForeignKey(PessoaFisica, on_delete=models.CASCADE)
    estabelecimento = models.ForeignKey(Estabelecimento, on_delete=models.CASCADE)
    ativo = models.BooleanField(verbose_name=u'Ativo', default=False)
    
    class Meta:
        unique_together = ('pessoa_fisica', 'estabelecimento')

class CoordenadorSus(models.Model):
    pessoa_fisica = models.ForeignKey(PessoaFisica, on_delete=models.CASCADE)
    ativo = models.BooleanField(verbose_name=u'Ativo', default=True)

class User(AbstractUser):
    class Meta:
        db_table = 'auth_user'

    def eh_profissional_saude(self):
        return ProfissionalSaude.objects.filter(pessoa_fisica__user=self).exists()
    
    def eh_coordenador_sus(self):
        return CoordenadorSus.objects.filter(pessoa_fisica__user=self).exists()

    def eh_paciente(self):
        return Paciente.objects.filter(pessoa_fisica__user=self).exists()

    def paciente(self):
        if Paciente.objects.filter(pessoa_fisica__user=self).exists():
            return Paciente.objects.filter(pessoa_fisica__user=self).first()
        return None

    def profissional_saude(self):
        if ProfissionalSaude.objects.filter(pessoa_fisica__user=self).exists():
            return ProfissionalSaude.objects.filter(pessoa_fisica__user=self).first()

templates/gestao/detalhar_estabelecimento.html
{% extends 'base.html' %}

{% load static %}

{% block css %}
    <link href="{% static 'libs/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/datatables/responsive.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/datatables/buttons.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'libs/jquery-toast/jquery.toast.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="page-title">{{estabelecimento.nome}} ({{estabelecimento.cnes}})</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Gestão</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'gestao:estabelecimentos' %}">Estabelecimentos</a></li>
                        <li class="breadcrumb-item active">{{estabelecimento.nome|title}}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="row" style="padding-bottom: 10px;">
        <div class="col-sm-12 offset-md-8 col-md-4 offset-lg-10 col-lg-2">    
            <a href="{% url 'gestao:editar_estabelecimento' estabelecimento.pk %}" class="btn btn-rounded btn-block btn-primary pull-right">Editar Estabelecimento</a>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Dados Cadastrais</h4>
                </div>
                            
                <div class="card-body">    
                    <table class="table table-striped dt-responsive nowrap">
                        <tr>
                            <th data-priority="1">CNES</th>
                            <td>{{estabelecimento.cnes}}</td>
                        </tr>
                    
                        <tr>
                            <th data-priority="1">Nome</th>
                            <td>{{estabelecimento.nome}}</td>
                        </tr>
                    
                        <tr>
                            <th data-priority="1">Contato</th>
                            <td>{{estabelecimento.telefone}}</td>
                        </tr>
                    
                        <tr>
                            <th data-priority="1">Endereço</th>
                            <td>{{estabelecimento.get_endereco}}</td>
                        </tr>
                    </table>
                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>

    <div class="row" style="padding-bottom: 10px;">
        <div class="col-sm-12 offset-md-8 col-md-4 offset-lg-10 col-lg-2">    
            <a href="{% url 'gestao:adicionar_profissional' estabelecimento.pk %}" class="btn btn-rounded btn-block btn-success pull-right">Adicionar Profissional</a>
        </div>
    </div>
    
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Profissionais</h4>
                </div>
                            
                <div class="card-body">    
                    <table id="tabela-prestadores" class="table table-striped dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th data-priority="1">#</th>
                                <th data-priority="1">Estabelecimento</th>
                                <th data-priority="1">Ativo</th>
                                <th data-priority="1">Ações</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for prof in profissionais_saude %}
                                <tr id="{{estabelecimento.estabelecimento__id}}">
                                    <td>{{prof.id}}</td>
                                    <td>{{prof.pessoa_fisica.nome }}</td>
                                    <td>
                                        {% if prof.ativo %}
                                            <span class="btn btn-success btn-rounded width-sm waves-effect waves-light">Sim</span>
                                        {% else %}                                 
                                            <span class="btn btn-danger btn-rounded width-sm waves-effect waves-light">Não</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if prof.ativo %}
                                            <a class="btn btn-rounded btn-danger" href="{% url 'gestao:desabilitar_profissional' estabelecimento.pk prof.pk %}">Desabilitar</a>
                                        {% else %}                                 
                                            <a class="btn btn-rounded btn-success" href="{% url 'gestao:habilitar_profissional' estabelecimento.pk prof.pk %}">Habilitar</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'libs/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.bootstrap4.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'libs/datatables/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.html5.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.flash.min.js' %}"></script>
    <script src="{% static 'libs/datatables/buttons.print.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'libs/datatables/dataTables.select.min.js' %}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.10.20/sorting/datetime-moment.js"></script>
    <script>
        $(document).ready(function() {
            //Buttons examples
            $('#tabela-prestadores').DataTable({
                "lengthMenu": [6, 12, 24, 48],
                "pageLength": 6,
                "language": {
                    "paginate": {
                        "previous": "<i class='mdi mdi-chevron-left'>",
                        "next": "<i class='mdi mdi-chevron-right'>"
                    },
                    "search": "Buscar:",
                    "info": "Exibindo registros de _START_ a _END_ para um total _TOTAL_ registros",
                    "emptyTable": "Nenhum registro encontrado",
                    "infoEmpty": "",
                    "loadingRecords": "Carregando fila...",
                    "processing": "Buscando registros...",
                    "zeroRecords": "Nenhum registro encontrado",
                    "lengthMenu": "Exibindo até _MENU_ registros por página"
                },
                "drawCallback": function () {
                    $('.dataTables_paginate > .pagination').addClass('pagination-rounded');
                }
            });
        });
    </script>
{% endblock %}

templates/gestao/form_base.html
{% extends "base.html" %}

{% load static %}

{% block css %}
    {{ form.media.css }}
    <link href="{% static 'libs/select2/select2.min.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="page-title">{{title}}</h4>
                
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item active">{{title}}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-12">
            <div class="card mt-3">
                <div class="card-header">
                    <h4>{{title}}</h4>
                </div>

                <div class="card-body">
                    {% if form.non_field_errors  %}
                        <div class="alert alert-danger">
                            Por favor, corrija o(s) erro(s) à seguir: <br/><br/>
                            <strong>{{ form.non_field_errors }}</strong>
                        </div>
                    {% endif %}
                    <form action="." method="post" id="login-form" class="parsley-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12">
                                {% for field in form %}
                                    <div class="form-group row mb-3">
                                        <label class="col-md-3 col-form-label" for="cns"> {{ field.label }}</label>
                                        <div class="col-md-9">
                                            {{ field }}
                                            <small>{{ field.help_text }}</small>
                                            <small><font color="red"><b>{{ field.errors }}</b></font></small>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div> <!-- end col -->
                        </div> <!-- end row -->
                        <ul class="list-inline wizard mb-0">
                            <div class="list-inline-item float-right">
                                <button class="btn btn-success btn-block width-lg" id="btn-login" type="submit"> Salvar </button>
                            </div>
                        </ul>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <!-- Datatables -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{% static 'libs/select2/select2.min.js' %}" defer></script>
    <script src="{% static 'libs/jquery-mask-plugin/jquery.mask.min.js' %}"></script>

    {{ form.media.js }}
    <script>
        $('[data-toggle="input-mask"]').each(function (idx, obj) {
            var maskFormat = $(obj).data("maskFormat");
            var reverse = $(obj).data("reverse");
            if (reverse != null)
                $(obj).mask(maskFormat, {'reverse': reverse});
            else
                $(obj).mask(maskFormat);
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            function limpa_formulario_cep() {
                // Limpa valores do formulário de cep.
                $("#id_logradouro").val("");
                $("#id_bairro").val("");
                $("#id_municipio").val("");
            }

            $("#id_cep").on('input', function () {
                //Nova variável "cep" somente com dígitos.
                var cep = $(this).val().replace(/\D/g, '');

                //Verifica se campo cep possui valor informado.
                if (cep != "") {
                    //Expressão regular para validar o CEP.
                    var validacep = /^[0-9]{8}$/;

                    //Valida o formato do CEP.
                    if (($(this).val().length === 9) & validacep.test(cep)) {
                        //Preenche os campos com "..." enquanto consulta webservice.
                        $("#id_logradouro").val("...")
                        $("#id_bairro").val("...")

                        //Consulta o webservice viacep.com.br/
                        $.getJSON("//viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {
                            if (!("erro" in dados)) {
                                //Atualiza os campos com os valores da consulta.
                                $("#id_logradouro").val(dados.logradouro);
                                if(dados.logradouro)
                                    $('#id_logradouro').prop('readonly', true);
                                else
                                    $('#id_logradouro').prop('readonly', false);
                                $("#id_bairro").val(dados.bairro);
                                if(dados.bairro)
                                    $('#id_bairro').prop('readonly', true);
                                else
                                    $('#id_bairro').prop('readonly', false);
                                $("#id_municipio").val(dados.localidade);

                                var id = null
                                var ibge = dados.ibge.slice(0, 6)
                                $.getJSON('/gestao/municipio/' + ibge, function(data){
                                    id = data.id

                                    $('#id_municipio').val(id).select2('trigger', 'select', {
                                        data: {
                                            id: id,
                                            text: dados.localidade.toUpperCase() + " / " + dados.uf
                                        }
                                    });

                                    if (dados.logradouro) {
                                        $('#id_numero').focus();
                                    } else {
                                        $('#id_logradouro').focus()
                                    }
                                })
                            } else {
                                //CEP pesquisado não foi encontrado.
                                limpa_formulario_cep();
                                alert("CEP não encontrado.");
                            }
                        });
                    } else if ($(this).val().length === 9) {
                        //cep é inválido.
                        limpa_formulario_cep();
                        alert("Formato de CEP inválido.");
                    }
                } else {
                    //cep sem valor, limpa formulário.
                    limpa_formulario_cep();
                }
            });
        });
    </script>
{% endblock %}