agenda/urls.py
from django.urls import path, include
from agenda import views

app_name = 'agenda'

urlpatterns = [
    path('', views.index, name='index'),
    path('autocadastro/', views.autocadastro, name='autocadastro'),
    path('minhas_vacinas/<int:paciente_pk>', views.minhas_vacinas, name='minhas_vacinas'),
    path(r'campanhas/', include([
        path('', views.campanhas, name='campanhas'),
        path('<int:pk>', views.detalhar_campanha, name='detalhar_campanha'),
        path('<int:pk>/editar/', views.editar_campanha, name='editar_campanha'),
        path('cadastrar/', views.cadastrar_campanha, name='cadastrar_campanha'),
    ])),
    path(r'agendar_vacinacao/', include([
        path('<int:campanha_pk>/', views.agendar_vacinacao_estabelecimento, name='agendar_vacinacao_estabelecimento'),
        path('<int:campanha_pk>/<int:estabelecimento_pk>/', views.agendar_vacinacao_data, name='agendar_vacinacao_data'),
    ])),
    
    path(r'acompanhar_vacinacao/', include([
        path('<int:agendamento_pk>/fila/', views.fila, name='fila'),
    ])),
    
    path('<int:agendamento_pk>/confirmar_vacinacao/', views.confirmar_vacinacao, name='confirmar_vacinacao'),
    path('cadastrar_vacina_privada/', views.cadastrar_vacina_privada, name='cadastrar_vacina_privada')

]

gestao/urls.py
from django.urls import path, include
from gestao import views

app_name = 'gestao'

urlpatterns = [
    path('sair/', views.sair, name='sair'),
    path('dashboard/<int:estabelecimento_pk>', views.dashboard_estabelecimento, name='dashboard_estabelecimento'),
    path('dashboard/', views.dashboard_geral, name='dashboard_geral'),
    path('municipio/<ibge>', views.busca_municipio),

    path(r'estabelecimentos/', include([
        path('', views.estabelecimentos, name='estabelecimentos'),
        path('<int:pk>', views.detalhar_estabelecimento, name='detalhar_estabelecimento'),
        path('<int:pk>/editar/', views.editar_estabelecimento, name='editar_estabelecimento'),
        path('cadastrar/', views.cadastrar_estabelecimento, name='cadastrar_estabelecimento'),
        path('<int:pk>/habilitar_prestador', views.habilitar_prestador, name='habilitar_prestador'),
        path('<int:pk>/adicionar_profissional/', views.adicionar_profissional, name='adicionar_profissional'),
        path('<int:estabelecimento_pk>/desabilitar_profissional/<int:profissional_pk>', views.desabilitar_profissional, name='desabilitar_profissional'),
        path('<int:estabelecimento_pk>/habilitar_profissional/<int:profissional_pk>', views.habilitar_profissional, name='habilitar_profissional'),
        path('<int:pk>/gestao_vacinas', views.gestao_vacinas, name='gestao_vacinas'),
        path('<int:estabelecimento_pk>/gestao_vacinas/cadastrar_estoque/<int:campanha_pk>/', views.cadastrar_estoque, name='cadastrar_estoque'),
        path('<int:pk>/campanhas/agendamentos', views.agendamentos, name='agendamentos'),
        path('<int:estabelecimento_pk>/agendamentos/cadastrar/<int:campanha_pk>/', views.cadastrar_agendamentos, name='cadastrar_agendamentos'),
        path('<int:pk>/agendamentos', views.agendamentos_estabelecimento, name='agendamentos_estabelecimento'),
    ])),
    
    path(r'coordenadores_sus/', include([
        path('', views.coordenadores_sus, name='coordenadores_sus'),
        path('adicionar/', views.adicionar_coordenador_sus, name='adicionar_coordenador_sus'),
        path('desabilitar_coordenador/<int:coordenador_pk>', views.desabilitar_coordenador, name='desabilitar_coordenador'),
        path('habilitar_coordenador/<int:coordenador_pk>', views.habilitar_coordenador, name='habilitar_coordenador'),        
    ])),
]

vacinas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.contrib.auth import views as auth_views
from vacinas import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('gestao/', include('gestao.urls')),
    path('agenda/', include('agenda.urls')),
    path('', include('social_django.urls', namespace='social')),
    path("select2/", include("django_select2.urls")),
    path('', views.index),
    path('accounts/login/', auth_views.LoginView.as_view()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [ url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT, }), url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_ROOT }), ]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="utf-8" />
        <title>Imunizow</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="Emerson Costa" name="author" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        {% block css %}{% endblock %}
        <!-- App favicon -->
        <link rel="shortcut icon" href="assets/images/favicon.ico">
        <!-- Bootstrap Css -->
        <link href="{% static 'css/bootstrap.min.css' %}" id="bootstrap-stylesheet" rel="stylesheet" type="text/css" />
        <!-- Icons Css -->
        <link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <!-- App Css-->
        <link href="{% static 'css/app.min.css' %}" id="app-stylesheet" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    </head>

    <body data-layout="horizontal" data-topbar="dark" data-layout-size="boxed">
        <!-- Begin page -->
        <div id="wrapper">
            {% include "navbar.html" %}
            <!-- ============================================================== -->
            <!-- Start Page Content here -->
            <!-- ============================================================== -->

            <div class="content-page">
                <div class="content">
                    <!-- Start Content-->
                    <div class="container-fluid">
                        {% block body %}{% endblock %}
                        <!-- end page title -->
                    </div> <!-- container-fluid -->                    
                </div> <!-- content -->

                <!-- Footer Start -->
                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                               Made with love in Grossos
                            </div>
                        </div>
                    </div>
                </footer>
                <!-- end Footer -->
            </div>

            <!-- ============================================================== -->
            <!-- End Page content -->
            <!-- ============================================================== -->

        </div>
        <!-- END wrapper -->

        <!-- Vendor js -->
        <script src="{% static 'js/vendor.min.js' %}"></script>

        <!-- App js -->
        <script src="{% static 'js/app.min.js' %}"></script>
        <script src="{% static 'libs/jquery-toast/jquery.toast.min.js' %}"></script>
        {% block scripts %}{% endblock %} 
    </body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% load static l10n %}

{% block css %}
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-flex align-items-center justify-content-between">
                <h4 class="page-title">Dashboard</h4>

                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-6">
            <figure class="highcharts-figure">
                <div id="container"></div>
                <p class="highcharts-description"></p>
            </figure>              
        </div>

        <div class="col-4">
            <div class="card-box">
                <h4 class="header-title mt-0 mb-4">Média de Vacinas Aplicadas por Dia</h4>
                <div class="widget-chart-1">
                    <div class="widget-detail-1 text-right">
                        <h2 class="font-weight-normal pt-2 mb-1"> {{atendimentos_por_dia}} </h2>
                        <p class="text-muted mb-1">Vacinas por dia</p>
                    </div>
                </div>
            </div>

        </div><!-- end col -->

    </div>
{% endblock %}

{% block scripts %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
    <script src="//cdn.datatables.net/plug-ins/1.10.20/sorting/datetime-moment.js"></script>
    <script> 
        pizza_agendamento = [
            {% for key, item in agendamentos.items %}
                {
                    name: '{{key|title}}',
                    y: {{item}},
                    sliced: true,
                    selected: true
                },
            {% endfor %}
        ];
    
        Highcharts.chart('container', {
            credits:{
                text: 'Imunizow'
            },
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            title: {
                text: 'Status de Agendamento'
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            accessibility: {
                point: {
                    valueSuffix: '%'
                }
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: true,
                        format: '<b>{point.name}</b>: {point.y} ({point.percentage:.1f}) %'
                    }
                }
            },
            series: [{
                name: 'Brands',
                colorByPoint: true,
                data: pizza_agendamento
            }]
        });
            
    </script>
{% endblock %}

templates/navbar.html
{% load static %}
<!-- Navigation Bar-->
<header id="topnav">
    <!-- Topbar Start -->
    <div class="navbar-custom">
        <div class="container-fluid">
            <ul class="list-unstyled topnav-menu float-right mb-0">

                <li class="dropdown notification-list">
                    <!-- Mobile menu toggle-->
                    <a class="navbar-toggle nav-link">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </a>
                    <!-- End mobile menu toggle-->
                </li>

                <li class="dropdown notification-list">
                    <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                        {% if request.session.foto_usuario %}
                            <img src="{{ request.session.foto_usuario }}" alt="user-image" class="rounded-circle">
                        {% endif %}
                        
                        <span class="pro-user-name ml-1">
                            {{user.username}} <i class="mdi mdi-chevron-down"></i> 
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                        <!-- item-->
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Bem Vindo !</h6>
                        </div>

                        <div class="dropdown-divider"></div>

                        <!-- item-->
                        <a href="{% url 'gestao:sair' %}" class="dropdown-item notify-item">
                            <i class="fe-log-out"></i>
                            <span>Sair</span>
                        </a>
                    </div>
                </li>
            </ul>

            <!-- LOGO -->
            <div class="logo-box">
                <a href="index.html" class="logo logo-light">
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-light.png' %}" alt="" height="16">
                    </span>
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-sm.png' %}" alt="" height="24">
                    </span>
                </a>
                <a href="index.html" class="logo logo-dark">
                    <span class="logo-lg">
                        <img src="{% static 'images/logo-dark.png' %}" alt="" height="16">
                    </span>
                    <span class="logo-sm">
                        <img src="{% static 'images/logo-sm.png' %}" alt="" height="24">
                    </span>
                </a>
            </div>

            <div class="clearfix"></div>
        </div> <!-- end container-fluid-->
    </div>
    <!-- end Topbar -->

    <div class="topbar-menu">
        <div class="container-fluid">
            <div id="navigation">
                <!-- Navigation Menu-->
                <ul class="navigation-menu">
                    {% if user.eh_profissional_saude %}
                        <li class="has-submenu">
                            <a href="{% url 'gestao:dashboard_estabelecimento' user.profissional_saude.estabelecimento.pk %}"><i class="mdi mdi-view-dashboard"></i>Dashboard</a>
                        </li>    
                    {% endif %}
                    
                    {% if user.eh_coordenador_sus %}
                        <li class="has-submenu">
                            <a href="{% url 'gestao:dashboard_geral' %}"><i class="mdi mdi-view-dashboard"></i>Dashboard</a>
                        </li>    
                    {% endif %}
                    
                    
                    {% if user.eh_paciente %}
                        <li class="has-submenu">
                            <a href="{% url 'agenda:index' %}"><i class="mdi mdi-view-dashboard"></i>Início</a>
                        </li>        
                        <li class="has-submenu">
                            <a href="{% url 'agenda:minhas_vacinas' user.paciente.pk %}"><i class="mdi mdi-view-dashboard"></i>Cartão de Vacinas</a>
                        </li>        
                        <li class="has-submenu">
                            <a href="#"><i class="mdi mdi-view-dashboard"></i>Vacinas</a>
                            <ul class="submenu megamenu">
                                <li>
                                    <ul>
                                        <li>
                                            <a href="{% url 'agenda:cadastrar_vacina_privada' %}">Cadastrar Vacina Privada</a>
                                        </li>                                        
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    {% endif %}
                    
                    {% if user.eh_coordenador_sus %}
                        <li class="has-submenu">
                            <a href="#"> <i class="mdi mdi-invert-colors"></i>Gestão<div class="arrow-down"></div></a>
                            <ul class="submenu megamenu">
                                <li>
                                    <ul>
                                        <li>
                                            <a href="{% url 'agenda:campanhas' %}">Campanhas</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'gestao:estabelecimentos' %}">Estabelecimentos</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'gestao:coordenadores_sus' %}">Coordenadores do SUS</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    {% endif %}
                    
                    {% if user.eh_profissional_saude %}
                        <li class="has-submenu">
                            <a href="{% url 'gestao:agendamentos_estabelecimento' user.profissional_saude.estabelecimento.pk %}"><i class="mdi mdi-book-account"></i>Fila</a>
                        </li>    

                        <li class="has-submenu">
                            <a href="#"><i class="mdi mdi-view-dashboard"></i>Agendamentos</a>
                            <ul class="submenu megamenu">
                                <li>
                                    <ul>
                                        <li>
                                            <a href="{% url 'gestao:agendamentos' user.profissional_saude.estabelecimento.pk %}">Cadastrar Agendamentos</a>
                                        </li>                                        
                                    </ul>
                                </li>
                            </ul>
                        </li>    
                        <li class="has-submenu">
                            <a href="{% url 'gestao:detalhar_estabelecimento' user.profissional_saude.estabelecimento.pk %}"><i class="mdi mdi-view-dashboard"></i>Meu Estabelecimento</a>
                        </li>    
                        <li class="has-submenu">
                            <a href="{% url 'gestao:gestao_vacinas' user.profissional_saude.estabelecimento.pk %}"><i class="mdi mdi-view-dashboard"></i>Gestão de Vacinas</a>
                        </li>    
                    {% endif %}
                </ul>
                <!-- End navigation menu -->

                <div class="clearfix"></div>
            </div>
            <!-- end #navigation -->
        </div>
        <!-- end container -->
    </div>
    <!-- end navbar-custom -->
</header>
<!-- End Navigation Bar-->